### ISSUE TITLE
Complete README and `meta.yaml` comments

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/sandbox#1]
@rwegener2 @rabernat, I believe this will work well.

If you click the Binder link in the `README`, you should be taken to a JupyterLab session with `recipe.py` already opened. Following the instructions at the top of `recipe.py` should make it clear how to open it as an executable notebook (this uses `jupytext`, but users need not concern themselves with the implementation).

My thought is that we will provide additional instructions in the README regarding how to open a PR, including:

1. Delete all the comments from `recipe.py`
2. Fork `staged-recipes` etc. etc.

I also need to complete similar commentary for `meta.yaml` to what is already in `recipe.py`, and `recipe.py` comments could use a bit more work too. Look forward to your feedback.

**Comment by rabernat** [comment]
Fantastic!

For interactive sessions, if we decide we need more RAM in the user environment, we can point it at https://aws-uswest2-binder.pangeo.io/ (github login required)

**Comment by rabernat** [comment]
> Following the instructions at the top of `recipe.py` should make it clear how to open it as an executable notebook

I can't help but wonder whether it is possible to get a direct link to the notebook (rather than the text file). For reference, here is the url we are using now:

https://mybinder.org/v2/gh/pangeo-forge/sandbox/binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fpangeo-forge%252Fsandbox%26urlpath%3Dlab%252Ftree%252Fsandbox%252Frecipe.py%26branch%3Dmain

**Comment by rwegener2** [comment]
This is really neat @cisaacstern!  Thoughts:

- The jupytext is impressive. It's nice how the `.py` file becomes a notebook. (Thanks for de-risking!)
- I like that you provided a template `recipe.py`. It seems like this nice commented `recipe.py` and `meta.yml` should also be in `staged-recipes`, so we have some duplication. I guess if Binder - Github integration was better we could just have the binder environment open staged recipes directly.
- Interesting that you included "INTERLUDE: INSPECT FILE PATTERN" in the template. My reaction was to remove it, since a user writing `recipe.py` should theoretically be writing their final draft of a recipe and not need to inspect objects. That raises the question, I think, are we thinking the main point of the sandbox is to build a final recipe, work on the tutorials, or both?

Looks really nice, Charles!

**Comment by cisaacstern** [comment]
> I can't help but wonder whether it is possible to get a direct link to the notebook (rather than the text file).

In the words of @gjoseph92 from [pangeo-forge-recipes#259](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/259#issuecomment-1012538763), I have been nerd-sniped

The binder link in the `README` now takes you directly to

<img width="800" alt="Screen Shot 2022-02-22 at 9 53 39 AM" src="https://user-images.githubusercontent.com/62192187/155190825-69149777-6cf5-420c-bc2d-9eb7c28a01a7.png">

I still need to update the commentary to remove the **Open With > Notebook** instructions.

**Comment by cisaacstern** [comment]
The custom workspace was created by:

1. Opening JupyterLab with the default workspace
2. Manually organizing the tabs into the desired configuration
3. Navigating to _**File > Save Current Workspace As...**_ and saving the workspace as `sandbox.jupyterlab-workspace`, then downloading and committing`sandbox.jupyterlab-workspace` to `main`
4. In the `README` Binder link, changing `urlpath%3Dlab%252Ftree%252Fsandbox%252Frecipe.py` to `urlpath%3Dlab%252Ftree%252Fsandbox%252Fsandbox.jupyterlab-workspace`

You will notice this now functions as a redirect: JupyterLab launches, opens `sandbox.jupyterlab-workspace`, and opening this file triggers the redirect to the three-pane layout. Maybe there's a way to do it without the redirect, but I'm not aware of how.

Now that we have the workspace spec in the repo root, maybe it makes sense to organize the content files (`recipe.py` and `meta.yaml`) into a subdirectory.

**Comment by cisaacstern** [comment]
> Now that we have the workspace spec in the repo root, maybe it makes sense to organize the content files (recipe.py and meta.yaml) into a subdirectory.

Done. Directory structure is now IMHO more readable as
```
.
├── LICENSE
├── README.md
├── recipe
│   ├── meta.yaml
│   └── recipe.py
└── sandbox.jupyterlab-workspace
```

I'll get on with the actual README / comments updates after a short detour to some other work.

> That raises the question, I think, are we thinking the main point of the sandbox is to build a final recipe, work on the tutorials, or both?

As Rachel and I just discussed offline, we are now thinking that this sandbox is really the same thing as the Intro Tutorial Part 3.

**Comment by cisaacstern** [comment]
rather than https://github.com/pangeo-forge/sandbox/issues/2#issue-1148502777, we'll just instruct users in the README to open a blank notebook in the existing sandbox, if they want a place to run the tutorials themselves

**Comment by cisaacstern** [comment]
> rather than https://github.com/pangeo-forge/sandbox/issues/2#issue-1148502777, we'll just instruct users in the README to open a blank notebook in the existing sandbox, if they want a place to run the tutorials themselves

Noting that in the end I did end up implementing #2 via #4
